apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-gitops-demo
  namespace: secure-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-gitops-demo
  template:
    metadata:
      labels:
        app: secure-gitops-demo
    spec:
      containers:
        - name: app
          image: lapuentesarah/secure-gitops-demo:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
