apiVersion: v1
kind: Service
metadata:
  name: secure-gitops-svc
  namespace: secure-gitops
spec:
  type: ClusterIP
  selector:
    app: secure-gitops-demo
  ports:
    - port: 80
      targetPort: 8080
